#!/usr/bin/env node

import { existsSync, readFileSync } from "node:fs";
import { createRequire } from "node:module";
import path from "node:path";

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { z } from "zod";

const require = createRequire(import.meta.url);
const { version } = require("../package.json") as { version: string };

// Bundled canonical artifacts, copied into build/bundled by `npm run build`.
// Byte-identical to the canonical sources in the repo (core/, template/) —
// generated by scripts/sync-adapters.sh; never hand-edited.
function bundled(name: string): string {
  return readFileSync(new URL(`./bundled/${name}`, import.meta.url), "utf8");
}

function protocolText(compact: boolean): string {
  return bundled(compact ? "mentor-protocol-compact.md" : "mentor-protocol.md");
}

interface OnboardingHit {
  path: string;
  content: string;
}

// Search dir/ONBOARDING.md, then walk up parent directories. Stop after
// checking the directory containing `.git` (the repo boundary), and never
// walk past the filesystem root.
function findOnboarding(startDir: string): OnboardingHit | null {
  let dir = path.resolve(startDir);
  for (;;) {
    const candidate = path.join(dir, "ONBOARDING.md");
    if (existsSync(candidate)) {
      return { path: candidate, content: readFileSync(candidate, "utf8") };
    }
    if (existsSync(path.join(dir, ".git"))) {
      return null;
    }
    const parent = path.dirname(dir);
    if (parent === dir) {
      return null;
    }
    dir = parent;
  }
}

const NOT_FOUND_MESSAGE =
  "No ONBOARDING.md found at or above that directory. " +
  "Use the `onboard` prompt to generate a draft from live source, " +
  "or author one from the template via codebase_mentor_get_template.";

const server = new McpServer({
  name: "codebase-mentor",
  version
});

// --- Tools -------------------------------------------------------------------

server.registerTool(
  "codebase_mentor_get_protocol",
  {
    title: "Get Mentor Protocol",
    description:
      "Return the codebase-mentor protocol text (the accuracy contract and operating modes). " +
      "Pass compact: true for the ~2 KB condensed variant.",
    inputSchema: {
      compact: z
        .boolean()
        .optional()
        .describe("Return the compact protocol instead of the full text. Defaults to false.")
    }
  },
  async ({ compact }) => textContent(protocolText(compact === true))
);

server.registerTool(
  "codebase_mentor_get_onboarding",
  {
    title: "Get Project ONBOARDING.md",
    description:
      "Locate and return the project's ONBOARDING.md by searching root, then walking up " +
      "parent directories (stopping after the directory containing .git). Returns the file " +
      "content and its path, or a not-found message suggesting the onboard prompt.",
    inputSchema: {
      root: z
        .string()
        .optional()
        .describe("Directory to start the search from. Defaults to the server's working directory.")
    }
  },
  async ({ root }) => {
    const hit = findOnboarding(root ?? process.cwd());
    if (!hit) {
      return textContent(NOT_FOUND_MESSAGE);
    }
    return textContent(`ONBOARDING.md found at ${hit.path}\n\n${hit.content}`);
  }
);

server.registerTool(
  "codebase_mentor_get_template",
  {
    title: "Get ONBOARDING.md Template and Authoring Guide",
    description:
      "Return the bundled ONBOARDING.md template and authoring guide for writing a new " +
      "ONBOARDING.md from scratch."
  },
  async () =>
    textContent(
      `# ONBOARDING.md template\n\n${bundled("ONBOARDING.template.md")}\n\n` +
        `---\n\n# Authoring guide\n\n${bundled("AUTHORING_GUIDE.md")}`
    )
);

// --- Prompts -----------------------------------------------------------------
// Packaged instructions the client model executes. The server supplies the
// protocol text and the task; the client's model does the reasoning.

const LOCATE_AND_VERIFY =
  "\n\nBefore answering, locate the project's ONBOARDING.md — call the " +
  "codebase_mentor_get_onboarding tool, or use your own file tools to find " +
  "ONBOARDING.md at or above the project root. Then follow the accuracy " +
  "contract: every claim backed by a symbol or file read in this session, " +
  "symbol anchors (never line numbers), and missing evidence declared explicitly.";

function mentorMessage(task: string): string {
  return `${protocolText(false)}${LOCATE_AND_VERIFY}\n\n${task}`;
}

server.registerPrompt(
  "mentor",
  {
    title: "Mentor",
    description: "Answer an architecture question with symbol-anchored evidence from live source.",
    argsSchema: {
      question: z.string().min(1).describe("The architecture question to answer.")
    }
  },
  ({ question }) => userMessage(mentorMessage(`Task — Mentor mode: ${question}`))
);

server.registerPrompt(
  "change_guide",
  {
    title: "Change Guide",
    description: "Produce an ordered, source-grounded checklist for making a change.",
    argsSchema: {
      task: z.string().min(1).describe("The change the developer wants to make.")
    }
  },
  ({ task }) => userMessage(mentorMessage(`Task — Change Guide mode: ${task}`))
);

server.registerPrompt(
  "reconcile",
  {
    title: "Reconcile",
    description: "Verify a claim about the codebase against live source: Confirmed / Stale / Indeterminate.",
    argsSchema: {
      claim: z.string().min(1).describe("The claim to verify against current source.")
    }
  },
  ({ claim }) => userMessage(mentorMessage(`Task — Reconcile mode: ${claim}`))
);

server.registerPrompt(
  "scan",
  {
    title: "Scan",
    description: "Freshness scan: verify every structural claim in ONBOARDING.md against current source."
  },
  () => userMessage(mentorMessage("Task — Scan mode: verify ONBOARDING.md against live source."))
);

server.registerPrompt(
  "onboard",
  {
    title: "Onboard",
    description: "Generate a draft ONBOARDING.md for a repo that has none, from live source plus the template.",
    argsSchema: {
      root: z
        .string()
        .optional()
        .describe("Project root to onboard. Defaults to the current working directory.")
    }
  },
  ({ root }) =>
    userMessage(
      `Generate a draft ONBOARDING.md for the project at ${root ?? "the current working directory"}.\n\n` +
        "Use this template as the structure:\n\n" +
        bundled("ONBOARDING.template.md") +
        "\n\nAuthoring guide:\n\n" +
        bundled("AUTHORING_GUIDE.md") +
        "\n\nScan the live source to fill every section; interview the developer only for what " +
        "source cannot show (ownership, gotchas, rationale). Every symbol anchor you write must " +
        "come from a file you actually read this session."
    )
);

// --- Resources ---------------------------------------------------------------

server.registerResource(
  "protocol",
  "codebase-mentor://protocol",
  {
    title: "Mentor Protocol",
    description: "The full codebase-mentor protocol text.",
    mimeType: "text/markdown"
  },
  async (uri) => ({
    contents: [{ uri: uri.href, mimeType: "text/markdown", text: protocolText(false) }]
  })
);

server.registerResource(
  "onboarding",
  "codebase-mentor://onboarding",
  {
    title: "Project ONBOARDING.md",
    description: "The current project's ONBOARDING.md, discovered by walking up from the working directory.",
    mimeType: "text/markdown"
  },
  async (uri) => {
    const hit = findOnboarding(process.cwd());
    return {
      contents: [
        {
          uri: uri.href,
          mimeType: "text/markdown",
          text: hit ? hit.content : NOT_FOUND_MESSAGE
        }
      ]
    };
  }
);

// --- Helpers -----------------------------------------------------------------

function textContent(text: string) {
  return { content: [{ type: "text" as const, text }] };
}

function userMessage(text: string) {
  return { messages: [{ role: "user" as const, content: { type: "text" as const, text } }] };
}

const transport = new StdioServerTransport();
await server.connect(transport);
